
server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/j1908?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: mybatis
    password: 123456

  jpa:
    database: mysql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qf.domain